### ISSUE TITLE
setModalData should return the modal instead of boolean to allow chaining

### ISSUE THREAD

**Issue by arshad115** [maximelafarie/ngx-smart-modal#168]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Currently the `setModalData` returns true or false based on if the data was set properly or not. 

**Expected behavior**

It should return the modal whose data has been set, to check if the data was set or not, chaining can be used. 

**What is the motivation / use case for changing the behavior?**

Method Chaining. Just after setting the modal data, may be you want to call the modal by `getModal`. Right now you have to write an extra line of code and its unnecessary. 

**Please tell us about your environment:**

NPM, VS code

* **Smart Modal version:** 7.1.0

* **Angular version:** 6

* **Browser:** [all]

* **Language:** [all]

**Comment by maximelafarie** [comment]
Hi @arshad115!

That's an interesting feature, I'm currently preparing a new release including fixes for #164 and some other little features, so it could be nice to add this one in the next release. Thank you! 👍

**Comment by arshad115** [comment]
Hi @maximelafarie 

Glad to hear that. May be I can also help with that. Thank you too :+1:

**Comment by maximelafarie** [comment]
After few investigations while fixing this issue is that it's a breaking change. It completely changes the return type of the method so it needs to be on the roadmap of the new features / refactor we want to make.
Stay tuned! 😉
