### ISSUE TITLE
Modal location (vertical horizontal) and size (width and height)

### ISSUE THREAD

**Issue by lguardado** [maximelafarie/ngx-smart-modal#222]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Hi all!
I'm trying to use a modal with certain height and width percentages (let's say 90% width and 80% height) vertically and horizontally centered.

**Expected behavior**
The modal shows centered in the screen with almost full width and height.

**Reproduction of the problem**
After reading the documentation carefully and these 3 issues:
https://github.com/biig-io/ngx-smart-modal/issues/113
https://github.com/biig-io/ngx-smart-modal/issues/103
https://github.com/biig-io/ngx-smart-modal/issues/101

I got to this conclusion: 
I couldn't use $dialog-position-top: x% since it wasn't centering the modal and if I remember right, it wasn't responsive either, so I created a custom class called `large-modal` with this style
```
.large-modal {
    max-width: none !important;
}
```
It worked for the horizontal width (not 90% exactly, but close enough and ok for what I needed) so far so good...

Then, looking for centering it vertically (and once again looking for issues and such) I checked the `target` parameter/option (didn't understand it 100%), but since in my case it was just centered in the screen, I assumed it wasn't related to what I needed.
So I added `nsm-centered` as a custom class (my first attempt was setting it as a regular class since it was from the library itself).

That fixed my center vertical issue, but it broken my horizontal width and center.

To fix this, I added to my `large-modal` class the style `justify-content: center` since the previous class (`nsm-centered`) had added `display: flex`. 

After that I couldn't find a way to get the width back, in another way than setting a `width: 100%` style to `nsm-content` (in the browser inspector) and which I'm not sure if I can achieve without ng-deep if I need to put it in my css and that still has some other styles avoiding it to have the actual 100% width... 
before going further I wanted to expose my issues here in case I'm missing something... maybe there is an easier way to do it, or maybe it could be an improvement to make in the library!

Thank you in advance!

(TLDR: short version)
I cant center vertically and horizontally a 90% x 80% modal using custom classes combined with 
`nsm-centered`

**What is the motivation / use case for changing the behavior?**
I need a centered big modal for showing big content

**Please tell us about your environment:**
MacOs, VsCode, npm

* **Smart Modal version:** 0.8.x
7.1.1

* **Angular version:** 2.0.x
6.1.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by maximelafarie** [comment]
I @lguardado and sorry for the late answer! Did you fixed it since the day you submit us this issue? I'll work on a Stackblitz reproduction and fix to see if there's something buggy about our classes or centering calculation. 😉 

Regards! 🖖
