### ISSUE TITLE
Class ref modal opening doesn't completely work

### ISSUE THREAD

**Issue by maximelafarie** [maximelafarie/ngx-smart-modal#235]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

If you want to inject a `Component` or a `TemplateRef` into a modal, the modal will only display the **static** content, not all the dynamic projected content as data provided through `@Input()` or `{{ ... }}`.

**Expected behavior**

Display the entire `Component` or `TemplateRef` as it will normally be.

**Reproduction of the problem**

[Bug reproduction here on StackBlitz](https://stackblitz.com/edit/angular-vwhbyc).

**What is the motivation / use case for changing the behavior?**

If a user uses the lib and wants to open a modal and inject into it an existing component with dynamic data projection, he couldn't.

**Please tell us about your environment:**

Not relevant.

* **Smart Modal version:** 0.8.x

7.2.1

* **Angular version:** 2.0.x

8.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Not relevant.

**Comment by maximelafarie** [comment]
I guess we could do something like in the official Angular example 😉 

Doc: https://angular.io/guide/dynamic-component-loader
Example: https://stackblitz.com/angular/vvxbeemekbl

**Comment by maximelafarie** [comment]
**Update note:** as said by @marco10024, it seems other projects also have this error like Angular Material Modals. It seems to be an error related to Angular and its design itself. But maybe some workaround will do the job... 🤔

**Comment by LouisAugry** [comment]
I'll try to work on it to find a solution. It could give us a distinct advantage over competing libraries ✌️😉

**Comment by GrzegorzTokarz** [comment]
I have made roughly working solution, but haven't got time to fix unit tests
https://github.com/GrzegorzTokarz/ngx-smart-modal/tree/feature/dynamic-content

**Comment by LouisAugry** [comment]
> I have made roughly working solution, but haven't got time to fix unit tests
> https://github.com/GrzegorzTokarz/ngx-smart-modal/tree/feature/dynamic-content

That's look good ! Thanks for helping us with this issue. I'm gonna take a closer look on this 😉

**Comment by maximelafarie** [comment]
@GrzegorzTokarz can you please make a PR to us? Even if the tests aren't passing, we will be able to fix it remotely on your fork then.
Great job tho! Thank you! 🖖

**Comment by GrzegorzTokarz** [comment]
@maximelafarie @LouisAugry here is PR with rough work, i'll rebase changes onto current, and clean up it a bit, it was just some speed solution for one of my projects

**Comment by emouawad** [comment]
Any Update on this? from what i have just tested it looks dynamic data in component still have issues?  
Shouldn't @GrzegorzTokarz Fix fixes this one?
