### ISSUE TITLE
[BUG] Cannot read property 'focus' of undefined on modal close

### ISSUE THREAD

**Issue by KrishnaSharmaCC** [maximelafarie/ngx-smart-modal#257]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Whenever i open the modal and close it, the modal gets closed but i get an exception in the console saying 
```
TypeError: Cannot read property 'focus' of undefined
    at ngx-smart-modal.js:1128
    at ZoneDelegate.invokeTask (zone.js:431)
    at Object.onInvokeTask (core.js:26247)
    at ZoneDelegate.invokeTask (zone.js:430)
    at Zone.runTask (zone.js:198)
    at ZoneTask.invokeTask (zone.js:513)
    at ZoneTask.invoke (zone.js:502)
    at timer (zone.js:3041)
```

**Expected behavior**
There should be no exception thrown.

**Reproduction of the problem**
My config for the modal is as follows :
```
<ngx-smart-modal
              #imageGallery
              identifier="imageGallery"
              customClass="nsm-dialog-animation-fade"
              class="imageGallery"
              (onOpen)="log('Modal opened!')"
              (onClose)="log('Modal closed!')"
              (onDismiss)="log('Modal dismissed!')"
              (onAnyCloseEvent)="modalClosed()"
              [dismissable]="false"
              [escapable]="false"
              [hideDelay]="100"
            >
              <!-- Rest of the code -->
</ngx-smart-modal>
```
Steps to reporduce: 
1. Configure the modal with the above options.
2. Open the modal.
3. Close the modal. We can notice the exception thrown in console.

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
OS: Win 10
Node: v10.16.0
Angular: 8.2

* **Smart Modal version:** 7.3.0

* **Angular version:** 8.2

* **Browser:** [all ]

* **Language:** [all ]

**Comment by khylias** [comment]
Hi @KrishnaSharmaCC,
thanks to reporting this issue. I've tried to duplicate your mistake, but I don't have the focus errors you're pointing out. Here is the stackblitz : [https://stackblitz.com/edit/ngx-smart-modal-lifecycle-ecvbzh](https://stackblitz.com/edit/ngx-smart-modal-lifecycle-ecvbzh)

Can you reproduce your error with a stackblitz ?

**Comment by KrishnaSharmaCC** [comment]
> 
> Can you reproduce your error with a stackblitz ?

@khylias, first of all, thanks for such a prompt reply.
I tried replicating this issue on stackblitz but it seems to be working fine there. So i think something else is going on here. Any help would be grateful.

I tried debugging the lib code in my app and found this:
When `onAnyCloseEvent` is fired, for some reason, `_this.lastElementFocused` stays undefined. 

![Kcl363cZOE](https://user-images.githubusercontent.com/42341447/71349673-9518b280-2595-11ea-8530-6fd886d39589.gif)

Again, thank you so much for the help @khylias !

**Comment by LouisAugry** [comment]
Hi @KrishnaSharmaCC 

`lastElementFocused` is set when you open the modal.

Can you show me your method `modalClosed `, because it seems you're doing something on close event

**Comment by KrishnaSharmaCC** [comment]
> Hi @KrishnaSharmaCC
> 
> `lastElementFocused` is set when you open the modal.
> 
> Can you show me your method `modalClosed() `, because it seems you're doing something on close event

Hi @LouisAugry, sorry for the late reply. But here is the `modalClosed()` definition
```
modalClosed() {
    this.logger.log('modal is closing');
    if (this.needCrop) {
      // If modal is force closed when the cropper is active, revert the current set item with prev set item.
      this.cropCanceled(this.selectedTab === 1 ? 'rectangle' : 'square');
    }
  }
```
The `if(this.needCrop)` block is to be ignored because it is not true. Rest of the code, there is nothing fancy going on, i am just logging a message.

Thanks again for looking into it.

**Comment by ish2028** [comment]
I ran across the same issue and I was calling `ngxModalService.open('modalName')`.  When I changed it to `ngxModalService.getModal('modalName').open()`, the error didn't happen again.

**Comment by KrishnaSharmaCC** [comment]
> I ran across the same issue and I was calling `ngxModalService.open('modalName')`. When I changed it to `ngxModalService.getModal('modalName').open()`, the error didn't happen again.

Thank you so much @ish2028. I tried using `.getModal(id).open()` fixes the issue. I am not getting the error anymore.
 I also noticed that a PR has already been created for this issue. Thanks @maximelafarie , @LouisAugry  for quick response.

**Comment by ricardosobrado** [comment]
Hello guys! 
I'm getting this error when I close a modal window that's called from other modal! Does anyone has any idea how to solve this? 

Here is where the error happens:
![2020-03-25_15h31_32](https://user-images.githubusercontent.com/41503481/77547922-1ee65d80-6eae-11ea-9143-dabe6f0d11d3.png)

NOTE: I'm using last version 7.4.0
Thank you in advance!

**Comment by maximelafarie** [comment]
Hi @ricardosobrado, there's an opened PR by @LouisAugry here: https://github.com/biig-io/ngx-smart-modal/pull/263 

I will merge it today and release a new version, it should fix your issue! 😉

**Comment by kiril-daskalov** [comment]
Still getting the same error on .closeAll()

**Comment by ricardosobrado** [comment]
Hi @maximelafarie! 
Unfortunately the error I reported still happens! Do you know if there's any perspective of looking into this issue?
Thank you!

**Comment by mmehranb** [comment]
if you dont need to focus on native element after modal close, set "refocus" option to false to avoid this error. its work for me

**Comment by ricardosobrado** [comment]
Thank you for your suggestion @mmehranb. It's enough for me.
