### ISSUE TITLE
Clicking on the scrollbar closes the modal

### ISSUE THREAD

**Issue by DanWebb** [maximelafarie/ngx-smart-modal#273]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Clicking the scrollbar will close the modal while a modal is open using the default `[dismissable]="true"` option.

Here's a short (23 sec) video showing the issue on the [demo page](https://biig-io.github.io/ngx-smart-modal/#/demo): https://www.loom.com/share/bc50384b5ecd4f88b9000256e7cc19b3

It happens because the overlay is a fixed element, then the scrollbar is part of the overlay.

**Expected behavior**

Clicking the scroll bar shouldn't close the modal

**Reproduction of the problem**

See [this video](https://www.loom.com/share/bc50384b5ecd4f88b9000256e7cc19b3)

**What is the motivation / use case for changing the behavior?**

Many people click and drag the scroll bar to move up and down.

**Smart Modal version:** 7.3.0

**Angular version:** 8.0.0

**Browser:** Tested in Chrome and Safari latest but sure it's in all of them

**Suggestions**

Adding `overflow-y: hidden` to the overlay then the following CSS to `.nsm-body` moves the scrollbar into the modal which fixes the issue...

```
  .nsm-body {
    max-height: calc(100vh - 1.75rem);
    overflow-y: auto;
  }
```

Alternatively, maybe an element could be added between the overlay and modal to attach the scrollbar to 🤔

**Protip:** if you're on mac set scrollbars to always visible in system settings to debug.

**Comment by maximelafarie** [comment]
Hi @DanWebb, thank you for this very complete issue! 😉 
I had massive work amount and quarantine didn't helped a lot... 😅 
I'll take a look at it very soon!
Cheers! 🤘

**Comment by maximelafarie** [comment]
Hi @DanWebb, it's finally fixed! Thank you for your patience 😉 
Cheers! 🖖

**Comment by DanWebb** [comment]
Hey @maximelafarie thanks for this, it's also taken me ages to reply, sorry! It looks like the fix would only handle dragging the scrollbar and not clicking on it, which many people do. Still, it seems like it'd cover the majority of cases 👍

The fixes I suggested still might be worth keeping in mind if anyone raises issues with clicking on the scrollbar in the future.
