### ISSUE TITLE
removeModal method doesn't remove ngx-smart-modal element from html dom

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [maximelafarie/ngx-smart-modal#277]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I use `removeModal` to be able to create new modal with new associated data (from https://github.com/biig-io/ngx-smart-modal/issues/173), but the corresponding ngx-smart-modal element is not removed from html. Is it the normal behavior or a bug?
Everytime I open my modal, I do like this:
```js
this.modalService.removeModal(MY_MODAL);
this.modalService.create(MY_MODAL, MyModalComponent)
   .setData(data)
   .open();
```

**Expected behavior**
ngx-smart-modal element should be remove from html dom, but I'd like to hear that if it's actually a feature or not.

**Reproduction of the problem**
Use the above code to **Open modals via class reference** without declaring a ngx-smart-modal element in template.

**What is the motivation / use case for changing the behavior?**
Prevent memory leak.

**Please tell us about your environment:**
* **Smart Modal version:** 7.4.0
* **Angular version:** 9
* **Browser:** Chrome
* **Language:** TypeScript

**Comment by maximelafarie** [comment]
Hi @Meigyoku-Thmn! Nice catch! I'll fix it asap 👌

**Comment by alexsherekin** [comment]
Hi @maximelafarie. Have you already started to work on this issue? If not, I'd like to look into it. It seems to be a good first issue to start contributing in the project.

**Comment by maximelafarie** [comment]
Hi @alexsherekin, thank you for your answer! Go for it buddy, I'll review it with pleasure!

**Comment by DziubinaElena** [comment]
Hi @alexsherekin. Could you please clarify when you are going to merge your pull request? Dozens of developers are looking forward to this and will be very grateful.

**Comment by alexsherekin** [comment]
Hi @DziubinaElena. I'd be glad to fix my PR, but it's currently blocked by another one https://github.com/maximelafarie/ngx-smart-modal/pull/304 which requires review from the maintainers. 
Folks, @maximelafarie @marco10024 @khylias @LouisAugry please, anyone, take a look

**Comment by kailo777** [comment]
hey @maximelafarie, 

Is there any release planned this year to solved that issue?

Best Regards

Kai
