### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by jamesamuel** [maximelafarie/ngx-smart-modal#282]
The documentation and demo links are returning 404 (https://biig-io.github.io/ngx-smart-modal).

Console error:
```Content Security Policy: The page's settings blocked the loading of a resource at https://biig-io.github.io/favicon.ico ("img-src").```

**Comment by khylias** [comment]
Hi @jamesamuel,

Thanks for bringing that up. 👍 
We will redeploy the documentation and demo as soon as possible.

**Comment by maximelafarie** [comment]
Will be fixed by #284! 🖖

**Comment by maximelafarie** [comment]
Version `7.4.1` with updated links has been released! Since it's a patch, it will be automatically updated for all users that aren't using a strict version. 👍 

Thank you @khylias and @jamesamuel for your awareness!
