### ISSUE TITLE
Associate modal to URL address

### ISSUE THREAD

**Issue by jamesamuel** [maximelafarie/ngx-smart-modal#283]
Is it possible to associate a modal to a URL (not query params)?

Creating modals based on triggers is fine in most cases, but sometimes a URL is required for UX reasons i.e. customers/create initiates a modal.

An example or workaround would suffice.

Keep up the good work!

**Comment by khylias** [comment]
Hi @jamesamuel 
I don't have the answer to your question. But I think you'll have a better chance of finding it on StackOverflow. It's not a library issue.

**Comment by maximelafarie** [comment]
@jamesamuel you're not very far from the result you want, just trigger a modal on `ngAfterViewInit` in the component associated to the route you want. I don't know if it's clear of if it's what you really want, but as @khylias said, you better may answer this question on StackOverflow. I'm often keeping an eye on the `ngx-smart-modal` tag / topic, so I will probably answer your question 😉 

Cheers! 🖖

**Comment by jamesamuel** [comment]
@maximelafarie Thanks for your suggestion.

It would be great if modals could be integrated into the router, where a modal contains a physical URL so that guards can be applied. 

Modals nowadays (especially in Angular or any SPA), don't contain just 'information', they contain forms. So guarding those forms would be amazing. I believe this is something that would perfect this package.

Thanks!
