### ISSUE TITLE
Documentation page showing 404 on Github Pages

### ISSUE THREAD

**Issue by mike-incipia** [maximelafarie/ngx-smart-modal#294]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Linking from README to docs returns 404.

**Expected behavior**
Docs load as they did yesterday and prior.

**Reproduction of the problem**
Click documentation link in README or go to [https://maximelafarie.com/ngx-smart-modal](https://maximelafarie.com/ngx-smart-modal)

**Please tell us about your environment:**
Github UI

**Browser:**
Chrome 84

**Comment by peavers** [comment]
This is actually really really annoying as I was right in the middle of implementing this throughout my project.

**Comment by maximelafarie** [comment]
Thank you @mike-incipia for reporting it. I'm on it, I'll bring it back to you asap guys, sorry for the inconvenience.

**Comment by maximelafarie** [comment]
@mike-incipia @peavers you've got access to the doc and the demo now! Sorry about this issue. Happy coding! :vulcan_salute:
