### ISSUE TITLE
🔥 NEWS, INFO AND FUTURE OF NGXSM 🚨

### ISSUE THREAD

**Issue by maximelafarie** [maximelafarie/ngx-smart-modal#310]
Hi all, 

First of all, I want to apologize for the loooong time without any info and/or support I brought to this project, there's a lot of things in my life that contributed this kind of delay (new house, new job and many more...).

I just would like to thank you all for keeping pushing issues to the repo and making some PRs. 

Now I'm stable in my life and got some time to spend, I want to catch up, and keep maintaining this repo in a good shape.

Here's my todo-list for this project:

1. (re)Read the issues and sort them
2. Make some milestones according to issues priority / new guidances I want to give to the repo
3. Check PRs
4. Update docs
5. Release a new version according to all merged (but unreleased) PRs
6. Fix issues
7. Work on an Angular 10/11 version

Keep library's users aware on the updates.

Again, thank you all for being and staying understanding and constructive all the time I was off.
Stay safe, take care and see ya! 🖖

**Comment by jwmcgettigan** [comment]
Hey @maximelafarie, I was wondering when do you think the next version will be released?  I currently need to download and build the package myself for the most updated version and it would be nice to be able to pull it from NPM.  I appreciate all the work you've done on this package and understand it's not a top priority for you.  Just figured I'd ask since it's been almost two years since the last release.

**Comment by denernun** [comment]
Mano, o cara não caga e nem sai da moita ! Libera esse pacote pro pessoal dar continuidade e não ficar criando fork de tudo quanto é jeito...coopera aí pô !

**Comment by maximelafarie** [comment]
> Mano, o cara não caga e nem sai da moita ! Libera esse pacote pro pessoal dar continuidade e não ficar criando fork de tudo quanto é jeito...coopera aí pô !

Dude, don't talk without knowing what can make that despite all the good will, some developers can't maintain a project at the pace they want or that you want.

You can also :
1. write in English to avoid people wasting their time with a translator
2. fork the project, modify it and make a PR
3. wait for me to do it, but without any guarantee of a deadline (even if I wanted to do all this a year ago)

Many developers who follow and use this library since I created it are (maybe too) compassionate and patient and even take the time to participate, but you are not one of them.

Cheers anyway. 🖖

**Comment by hiepxanh** [comment]
@maximelafarie  can you make an update for Angular 16 please, I love this library so much, I hope you can do a small upgrade?

**Comment by maximelafarie** [comment]
Hi @hiepxanh, thank you for the kind words. 
A (great) guy just helped me being motivated enough to make an angular-ivy-compatible upgrade on ngx-smart-modal. So i'm currently (really) working on it.

I'm doing my best to get this version released as soon as possible.

I'm going to clean up a lot of the tickets, as the library will no longer be built the same way, but more on the "[official](https://angular.io/guide/creating-libraries#getting-started)" Angular pattern.

This version will probably be a big jump from 7.x to 14.x.

Since I want to get this update out quickly, I may skip the demo update for a while, while I make a more up-to-date one.

Documentation, method and function names will remain the same, as I want to keep breaking changes to a minimum.

Have a nice day ngx-smart-modal folks and thx for your support. 🙏

🖖

**Comment by hiepxanh** [comment]
that a really good news, my application still work with your libary, I will keep working and wait for your update <3 Thank you so much for a great library and enthusiasm in this

**Comment by maximelafarie** [comment]
Phew... 🥵

All the hard work has been done.

The code is now back on track, following Angular's recommendations for libraries in terms of development, build and publication, etc.

So I've opened a PR (#376) where you can find my progress in detail.

There will be some small modifications, but they shouldn't be too hard for you to change. I'll detail them all in the changelog and in the Readme, which will serve as documentation for a while, since the old project tree contained the documentation, demo and library. Now it's cleaner!

I hope to be able to finalize the remaining tasks tomorrow evening and publish a new version in the process!

Thank you all for your patience and encouragement, which really helped me to keep going! 🙏 

🖖

**Comment by hiepxanh** [comment]
Well done sir :clap :clap :clap

**Comment by hiepxanh** [comment]
Amazing work 😍😍😍

**Comment by khylias** [comment]
Nice job! Congrats :partying_face:

**Comment by hiepxanh** [comment]
I already upgrade and test with angular 16 standalone version. It's still working as expect. Thank you so much sir  💯

**Comment by maximelafarie** [comment]
Awesome! 🤘 Thank you very much for your feedback @hiepxanh 🙏
