### ISSUE TITLE
Support for Angular 16 (Ivy compatibility without ngcc)

### ISSUE THREAD

**Issue by Way** [maximelafarie/ngx-smart-modal#375]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
'NgxSmartModalModule' does not appear to be an NgModule class.
This likely means that the library (ngx-smart-modal) which declares NgxSmartModalModule is not compatible with Angular Ivy. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Expected behavior**
Is there any chance of an upgrade to be compatible with Ivy for the newest Angular 16 version?

**Reproduction of the problem**
Try to install and use ngx-smart-modal inside an Angular 16 application will fail because it's missing Ivy compatibility.

**What is the motivation / use case for changing the behavior?**
Angular Compatibility Compiler (ngcc) has been removed.

**Please tell us about your environment:**

* **Smart Modal version:** 7.4.1

* **Angular version:** 16

**Comment by maximelafarie** [comment]
Hi @Way 

You're right, I'm working on this : https://github.com/maximelafarie/ngx-smart-modal/issues/310#issuecomment-1637672646 

🖖

**Comment by maximelafarie** [comment]
Version `14.0.2` has been released on NPM! 🤘
